name: details events
on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - opened
  #   branches:
  #     - master
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
