# create 2 wf:
#   Lint, test & deploy on 'push'
#   Output event details on "issues"

name: output event details
on: 
  # issues:
  workflow_dispatch:
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"