name: test job artifacts output caching
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run test
        run: npm run test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Deploy
        run: echo "Deploying..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run test
        run: npm run test
      - name: Download artifacts
      - uses: actions/download-artifact@v4
        with:
          name: dist-without-markdown
      - name: Output files
        run: ls 
      - name: Deploy
        run: echo "Tesing..."
